apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      nodeSelector:
        role: app
      containers:
        - name: express
          image: zulkarnen/example-express:latest # Replace with your actual image
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/postgres"
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
