apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      nodeSelector:
        role: app
      containers:
        - name: express
          image: zulkarnen/example-express:latest # Replace with your actual image
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/postgres"
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          # Liveness Probe to ensure the container is healthy
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # Readiness Probe to ensure the container is ready to serve traffic
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
