apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
  namespace: myapp
spec:
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce